package zendo.playground.quizzes;
/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */

public class Test {

    public static void main(String[] args) {
    }
	
}