<wsdl:definitions targetNamespace="http://test.ro/product-service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:schema="http://test.ro/product-schema"
    xmlns:tns="http://test.ro/product-service">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://test.ro/product-schema" schemaLocation="main-schema.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="GetProductByIdRequestMessage">
        <wsdl:part name="GetProductByIdRequestPart" element="schema:GetProductByIdRequest" />
    </wsdl:message>

    <wsdl:portType name="ProductServicePortType">
        <wsdl:operation name="GetProductById">
            <wsdl:input name="GetProductByIdRequest" message="tns:GetProductByIdRequestMessage" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ProductServiceBinding" type="tns:ProductServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="GetProductById">
            <soap:operation soapAction="http://test.ro/product-service/get-product-by-id" />
            <wsdl:input name="GetProductByIdRequest">
                <soap:body use="literal" />
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ProductService">
        <wsdl:port binding="tns:ProductServiceBinding" name="ProductServicePort">
            <soap:address location="http://localhost:8080/ps-springws/productService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>